services:
  indi:
    build:
      context: ./indi
    image: indi
    container_name: indi
    platform: linux/amd64
    command: indiserver indi_simulator_telescope indi_simulator_ccd
    ports:
      - "7624:7624"
  api:
    build:
      context: ./api
    image: api
    container_name: api
    platform: linux/amd64
    command: python3 main.py
    ports:
      - "8888:8888"
    volumes:
      - ./api:/app
    depends_on:
      - indi

